// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/login": {
            "post": {
                "description": "Get JWT token for access all APIs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "description": "LoginDto.go",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success (UserDto.go)",
                        "schema": {
                            "$ref": "#/definitions/user.UserDto"
                        }
                    }
                }
            }
        },
        "/v1/user/delete/{id}": {
            "delete": {
                "description": "delete",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success (UserDto.go)",
                        "schema": {
                            "$ref": "#/definitions/user.UserDto"
                        }
                    }
                }
            }
        },
        "/v1/user/list": {
            "get": {
                "description": "list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success (UserDto.go)",
                        "schema": {
                            "$ref": "#/definitions/user.UserDto"
                        }
                    }
                }
            }
        },
        "/v1/user/save": {
            "post": {
                "description": "save",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "save",
                "parameters": [
                    {
                        "description": "UserDto.go",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserDto"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success (UserDto.go)",
                        "schema": {
                            "$ref": "#/definitions/user.UserDto"
                        }
                    }
                }
            }
        },
        "/v1/user/update/{id}": {
            "put": {
                "description": "update",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "UserDto.go",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success (UserDto.go)",
                        "schema": {
                            "$ref": "#/definitions/user.UserDto"
                        }
                    }
                }
            }
        },
        "/v1/user/view/{id}": {
            "get": {
                "description": "view",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "view",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success (UserDto.go)",
                        "schema": {
                            "$ref": "#/definitions/user.UserDto"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginDto": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                },
                "username": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                }
            }
        },
        "user.UserDto": {
            "type": "object",
            "required": [
                "name",
                "password",
                "username"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                },
                "password": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                },
                "username": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                }
            }
        }
    },
    "securityDefinitions": {
        "Authorization": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.1.0",
	Host:             "localhost:8810",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Demo Swagger-UI (GO+GORILLA MUX) for Nexsoft Project",
	Description:      "Implement swagger-ui on Go project with Gorilla Mux (web framework) + JWT Authorization",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
